### ISSUE TITLE
Regression code déterminiation fedCode

### ISSUE THREAD

**Issue by gpiroux** [medispring/icc-api#111]
Le code ci-dessous n'est pas équivalent: on peut avoir des defCodes sur plus de 3 position (example Partena - Mutualité libre: "509,527")
=> Hors ils sont équivalents au code "509", d'où le substr! 

Pas sur que ça arrive avec les fédérations parentes mais ce n'est pas a exclure.

![screen shot 2019-02-13 at 22 00 13](https://user-images.githubusercontent.com/2011650/52743799-2664e300-2fdb-11e9-8ca7-4432e7d31865.png)

**Comment by antoinepairet** [comment]
Good catch. 

A priori, 2 federations ne vont pas fusionner.
Les mutuelles sont encouragées à fusionner pour atteindre une taille critique et réaliser des économies d'échelle.
